import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";

const poppinsSans = Poppins({
  weight: ["400", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={`${poppinsSans.className} antialiased`}>{children}</body>
    </html>
  );
}
